# Generated by Django 5.1.5 on 2025-02-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehiculos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspeccionAccesorios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("responsable", models.CharField(max_length=100)),
                ("cricket", models.BooleanField(default=False)),
                ("matafuegos", models.BooleanField(default=False)),
                ("stereo", models.BooleanField(default=False)),
                ("navegador", models.BooleanField(default=False)),
                ("bateria", models.BooleanField(default=False)),
                ("tuercas_seguridad", models.BooleanField(default=False)),
                ("manuales", models.BooleanField(default=False)),
                ("duplicado_llaves", models.BooleanField(default=False)),
                (
                    "cubierta_DI_marca",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cubierta_DI_rodado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cubierta_DD_marca",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cubierta_DD_rodado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cubierta_TI_marca",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cubierta_TI_rodado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cubierta_TD_marca",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cubierta_TD_rodado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "auxilio_marca",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "auxilio_rodado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bateria_marca",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bateria_amperaje", models.IntegerField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculos.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspeccionExterior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("responsable", models.CharField(max_length=100)),
                ("carroceria", models.BooleanField(default=False)),
                ("pintura", models.BooleanField(default=False)),
                ("parabrisas_ventanas", models.BooleanField(default=False)),
                ("faros_luces", models.BooleanField(default=False)),
                ("neumaticos", models.BooleanField(default=False)),
                ("espejos_retrovisores", models.BooleanField(default=False)),
                ("limpiaparabrisas", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculos.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspeccionInterior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("responsable", models.CharField(max_length=100)),
                ("asientos", models.BooleanField(default=False)),
                ("tablero", models.BooleanField(default=False)),
                ("climatizacion", models.BooleanField(default=False)),
                ("sistema_audio", models.BooleanField(default=False)),
                ("alfombras_tapetes", models.BooleanField(default=False)),
                ("airbag", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculos.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspeccionMecanica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("responsable", models.CharField(max_length=100)),
                ("motor", models.BooleanField(default=False)),
                ("niveles_liquidos", models.BooleanField(default=False)),
                ("bateria", models.BooleanField(default=False)),
                ("transmision", models.BooleanField(default=False)),
                ("frenos", models.BooleanField(default=False)),
                ("suspension", models.BooleanField(default=False)),
                ("escape", models.BooleanField(default=False)),
                ("revision_emisiones", models.BooleanField(default=False)),
                ("arranque_motor", models.BooleanField(default=False)),
                ("radiador", models.BooleanField(default=False)),
                ("estado_embrague", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculos.vehiculo",
                    ),
                ),
            ],
        ),
    ]
