# Generated by Django 5.1.5 on 2025-02-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehiculos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comprador", models.CharField(max_length=100)),
                ("dni_comprador", models.CharField(max_length=10)),
                ("fecha_transferencia", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En proceso", "En proceso"),
                            ("Completada", "Completada"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                ("titulo_vehiculo", models.BooleanField(default=False)),
                ("form_08", models.BooleanField(default=False)),
                ("cedula_verde", models.BooleanField(default=False)),
                ("cedula_azul", models.BooleanField(default=False)),
                ("verificacion_policial", models.BooleanField(default=False)),
                ("informe_historico_dominio", models.BooleanField(default=False)),
                ("cuil_cuit_comprador", models.BooleanField(default=False)),
                ("dni_conyuge", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "vehiculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculos.vehiculo",
                    ),
                ),
            ],
        ),
    ]
