# Generated by Django 5.1.5 on 2025-02-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dominio", models.CharField(max_length=10, unique=True)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("año", models.PositiveIntegerField()),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(max_length=30)),
                ("kilometros", models.PositiveIntegerField()),
                (
                    "tipo_combustible",
                    models.CharField(
                        choices=[
                            ("Nafta", "Nafta"),
                            ("Diesel", "Diesel"),
                            ("Nafta/GNC", "Nafta/GNC"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transmision",
                    models.CharField(
                        choices=[("Manual", "Manual"), ("Automático", "Automático")],
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
