# Generated by Django 5.1.5 on 2025-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiculo",
            name="fecha_registro",
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="año",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="kilometros",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="tipo_combustible",
            field=models.CharField(
                choices=[
                    ("Nafta", "Nafta"),
                    ("Diesel", "Diesel"),
                    ("Nafta/GNC", "Nafta/GNC"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="transmision",
            field=models.CharField(
                choices=[("Manual", "Manual"), ("Automático", "Automático")],
                max_length=10,
            ),
        ),
    ]
